# Rakeile:

require 'houston'

ROOT = File.expand_path(File.dirname(__FILE__))

task :push_notification do
  # Environment variables are automatically read, or can be overridden by any specified options. You can also
  # conveniently use `Houston::Client.development` or `Houston::Client.production`.
  APN = Houston::Client.development
  APN.certificate = File.read("./development_com.dezamisystem.app.buyer.pem")
  # An example of the token sent back when a device registers for notifications
  token = "<77722c23 f71fbebe a1d69d39 6952ef2a 5e1890be ac462d07 b720edb4 7604a2c7>"
  # token = ENV['DEVICE_TOKEN']

  # Create a notification that alerts a message to the user, plays a sound, and sets the badge on the app
  notification = Houston::Notification.new(device: token)
  notification.alert = "Hello, World!"

  # Notifications can also change the badge count, have a custom sound, have a category identifier, indicate available Newsstand content, or pass along arbitrary data.
  notification.badge = 98 
  notification.sound = "sosumi.aiff"
  notification.category = "INVITE_CATEGORY"
  notification.content_available = true
  notification.custom_data = {foo: "bar"}

  # And... sent! That's all it takes.
  APN.push(notification)
end
