# Rakeile:

require 'houston'

ROOT = File.expand_path(File.dirname(__FILE__))

task :push_notification do
  # Environment variables are automatically read, or can be overridden by any specified options. You can also
  # conveniently use `Houston::Client.development` or `Houston::Client.production`.
  APN = Houston::Client.development
  APN.certificate = File.read("./production_com.dezamisystem.app.buyer.pem")
  # An example of the token sent back when a device registers for notifications
  # token = "<bf3625a0 bb13bc71 e0438c6f 12435503 d4c8dce0 5a5a7506 c1d3d22a 7d295638>"
  token = "bf3625a0bb13bc71e0438c6f12435503d4c8dce05a5a7506c1d3d22a7d295638"

  # Create a notification that alerts a message to the user, plays a sound, and sets the badge on the app
  notification = Houston::Notification.new(device: token)
  notification.alert = "Hello, Good by my World!"

  # Notifications can also change the badge count, have a custom sound, have a category identifier, indicate available Newsstand content, or pass along arbitrary data.
  notification.badge = 18
  notification.sound = "sosumi.aiff"
  notification.category = "INVITE_CATEGORY"
  notification.content_available = true
  notification.custom_data = {custom_data: "json format"}

  # And... sent! That's all it takes.
  APN.push(notification)
end
